version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.10
    working_directory: ~/mapbox-gl-js
    steps:
      - checkout
      - restore_cache:
          key: v1-mapbox-gl-js-cache
      - run:
          name: install dependencies
          command: |
            bash ./.circleci/dependencies.sh
      - save_cache:
          key: v1-mapbox-gl-js-cache
          paths:
            - '~/.yarn'
            - '.eslintcache'
            - 'node_modules'
      - run: sudo apt-get update && sudo apt-get install build-essential libglew-dev libxi-dev
      - run:
          name: run tests
          command: |
            bash ./.circleci/test.sh
      - store_artifacts:
          path: "test/integration/render-tests/index.html"
      - store_artifacts:
          path: "test/integration/query-tests/index.html"
      - run:
          name: deploy if tagged
          command: |
            if [ $CIRCLE_TAG =~ /v[0-9]+\.[0-9]+\.[0-9]+(\-dev)?/ ]; then
              bash ./deploy.sh
            fi
